### ISSUE TITLE
Youtube URL embed_not_allowed Error 

### ISSUE THREAD

**Issue by aposto** [LonelyCpp/react-native-youtube-iframe#98] opened 2021-01-13 04:04 UTC
An error occurs in a specific video.
Its address is a 'NznZsidSq8s';

I tried putting 'Origin'  as an argument, but I still get an embed_not_allowed error.

**Comment by LonelyCpp** [comment] 2021-01-13 05:14
hey, the base URL is not exposed in `v1.4.0`. Point the package to the master branch in your `package.json`, then specifying baseUrl 

(more info here - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/89)

**Comment by aposto** [comment] 2021-01-13 16:38
Thank you so much for your quick feedback.

But, Your solution doesn't work. 
Even the normal video is not rendered on the screen at all. Have you ever tried it yourself?

```
  "react-native-youtube-iframe": "https://github.com/lonelyCpp/react-native-youtube-iframe#master"

  webViewProps={{
        source: { baseUrl: "https://youtube.com" },
  }}

```

> hey, the base URL is not exposed in `v1.4.0`. Point the package to the master branch in your `package.json`, then specifying baseUrl
> 
> (more info here - #89)

**Comment by LonelyCpp** [comment] 2021-01-14 15:55
Yo, I'm sorry. This was not fully tested (hence not already on a release). 

It seems like adding `baseUrl` fixes the problem for android, but completely breaks on iOS. Don't see a solid fix for this yet.

**Comment by ahmadysalah** [comment] 2021-01-14 21:11
Thanks for u r efforts here, I am asking for this either have the same error. so can I add my API key in any way using this fantastic component, ???

**Comment by LonelyCpp** [comment] 2021-01-15 15:46
@ahmadysalah the iframe API doesn't have options to pass in API keys unfortunately. :(

**Comment by aposto** [comment] 2021-01-16 02:10
https://github.com/hmhv/YoutubePlayer-in-WKWebView/blob/master/WKYTPlayerView/WKYTPlayerView.bundle/Assets/YTPlayerView-iframe-player.html

This is the html of the 'https://github.com/hmhv/YoutubePlayer-in-WKWebView' used in 'react native youtube' 

Anything that could help?

**Comment by ahmadysalah** [comment] 2021-01-16 16:56
Thanks @aposto and @LonelyCpp, so i cant send my api as props to the component,
I still have the same error with some embeded vides.

**Comment by ahmadysalah** [comment] 2021-01-22 00:23
it's worked, thanks @aposto  :+1:

**Comment by nteguziejko** [comment] 2021-01-22 09:37
So what you ended up doing @ahmadysalah? I have the same issue :(

**Comment by ahmadysalah** [comment] 2021-01-22 20:48
> Thank you so much for your quick feedback.
> 
> But, Your solution doesn't work.
> Even the normal video is not rendered on the screen at all. Have you ever tried it yourself?
> 
> ```
>   "react-native-youtube-iframe": "https://github.com/lonelyCpp/react-native-youtube-iframe#master"
> 
>   webViewProps={{
>         source: { baseUrl: "https://youtube.com" },
>   }}
> ```
> 
> > hey, the base URL is not exposed in `v1.4.0`. Point the package to the master branch in your `package.json`, then specifying baseUrl
> > (more info here - #89)

add this repo link instead of version of this module 
and add source youtube as iframe params,  :100:

**Comment by nteguziejko** [comment] 2021-01-25 08:38
Thanks @ahmadysalah, though it's still not working. This solution works for android but not for IOS. If I use webview prop then it is not rendering on ios at all - if I don't use it I have video thumbnail but video itself is unavailable ...

**Comment by ahmadysalah** [comment] 2021-01-25 19:36
i face this problem eather, for acoble of day , so @LonelyCpp is there any update on repo ?

**Comment by LonelyCpp** [comment] 2021-01-26 03:41
This is a bug from react-native-webview - https://github.com/react-native-webview/react-native-webview/issues/517. Fixing that would be out of scope here. 

Although I'm trying some alternate options to get it to work by loading a script from a hosted server. No promises tho 😕

**Comment by ahmadysalah** [comment] 2021-01-26 21:17
I here about that eather they need some help there in comunity, so its nut effect in production right now it can be wait. Thanks for u r help.

I dont know if expo use another web view module in there core as i saw in expo documentation before, so i prefere if we can implement ifram and test it.

**Comment by axeljeremy7** [comment] 2021-02-03 19:31
is this is connected to ads?
- this video fails, https://youtu.be/DVtNve4qySA
- this video pass, https://youtu.be/YXMo5w9aMNs

- For android I did the trick with webViewProps.
- in iOS the videoId seems sufficient sometime

**Comment by LonelyCpp** [comment] 2021-02-12 06:28
Hi everyone, I have some exciting news! 

I've found a reliable fix for this issue, where not having a domain results in "embed_not_allowed" for many videos.
 
- update dependency in `package.json` to  

```
"react-native-youtube-iframe": "https://github.com/LonelyCpp/react-native-youtube-iframe#remote-source"
```

It would be great if everyone can give this a try. 

This still a very early preview, I will be working on cleaning it up if all goes well 😄 

Some video IDs that you guys can test on - 
* `NznZsidSq8s`
* `DVtNve4qySA`
* `o1KWG3yRd2k`
* `HCjNJDNzw8Y`

**Comment by joelpanor** [comment] 2021-02-14 12:54
HEy,

I have this error when I try to install "Could not resolve dependency"

**Comment by LonelyCpp** [comment] 2021-02-15 06:02
@joelpanor make sure you've copied the branch name properly.
alternatively you can do 
```
npm install LonelyCpp/react-native-youtube-iframe#remote-source
```
or
```
yarn add LonelyCpp/react-native-youtube-iframe#remote-source
```

**Comment by axeljeremy7** [comment] 2021-02-17 18:57
@LonelyCpp I try both GitHub and yarn add I have error: 
Error: While trying to resolve module `react-native-youtube-iframe` from file `/Users/axel/Work/DSP-Mobile/tag1.0/dsp/src/screens/Draft/YoutubeVideoPlayer.js`, the package `/Users/axel/Work/DSP-Mobile/tag1.0/dsp/node_modules/react-native-youtube-iframe/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/axel/Work/DSP-Mobile/tag1.0/dsp/node_modules/react-native-youtube-iframe/dist/index.js`. Indeed, none of these files exist:

**Comment by LonelyCpp** [comment] 2021-02-17 19:18
seems like some kind of build issue in node_module. The main branch has an extra build step to support react-native-web.

can you check this [stackoverflow thread](https://stackoverflow.com/questions/60124435/however-this-package-itself-specifies-a-main-module-field-that-could-not-be-r)?
also maybe removing node_modules, then reinstalling packages

**Comment by axeljeremy7** [comment] 2021-02-17 21:34
@LonelyCpp I did that and it worked.

**Comment by Priiyam** [comment] 2021-02-26 08:55
Hi @LonelyCpp , its working great! I have however noticed one bug on **iOS** as soon as i shifted to this new package. Its as follows:
When your iOS device is on portrait > play the video while on portrait > hit the fullscreen button while on portrait > Now turn your device to landscape while on fullscreen. 

At this point the DImensions API and useWindowDimensions from react native shows the opposite values for width. Meaning shorter width for landscape while larger width values on portrait (they basically get interchanged, landscape width is shown while on potrait while potrait width is shown on landscape). This however fixes when i exit from fullscreen and it behaves normally.

Can you look into this issue? As i heavily depend on the screen width to make this responsive for portrait and landscape mode. And the issue is only on iOS. On android it works normally.

**Comment by Priiyam** [comment] 2021-02-26 08:55
> Hi everyone, I have some exciting news!
> 
> I've found a reliable fix for this issue, where not having a domain results in "embed_not_allowed" for many videos.
> 
> * update dependency in `package.json` to
> 
> ```
> "react-native-youtube-iframe": "https://github.com/LonelyCpp/react-native-youtube-iframe#remote-source"
> ```
> 
> It would be great if everyone can give this a try.
> 
> This still a very early preview, I will be working on cleaning it up if all goes well 😄
> 
> Some video IDs that you guys can test on -
> 
> * `NznZsidSq8s`
> * `DVtNve4qySA`
> * `o1KWG3yRd2k`
> * `HCjNJDNzw8Y`

Hi @LonelyCpp , its working great! I have however noticed one bug on iOS as soon as i shifted to this new package. Its as follows:
When your iOS device is on portrait > play the video while on portrait > hit the fullscreen button while on portrait > Now turn your device to landscape while on fullscreen.

At this point the DImensions API and useWindowDimensions from react native shows the opposite values for width. Meaning shorter width for landscape while larger width values on portrait (they basically get interchanged, landscape width is shown while on potrait while potrait width is shown on landscape). This however fixes when i exit from fullscreen and it behaves normally.

Can you look into this issue? As i heavily depend on the screen width to make this responsive for portrait and landscape mode. And the issue is only on iOS. On android it works normally.

**Comment by LonelyCpp** [comment] 2021-03-28 15:31
this is fixed in `v2.0.0` 🥳

**Closed by LonelyCpp** 2021-03-28 15:31 UTC

**Comment by lftoma** [comment] 2021-04-07 02:54
Hey @LonelyCpp! Great news, wanted to know if the adds issue is also fixed in this new version? Thanks mate!

**Comment by LonelyCpp** [comment] 2021-04-07 05:25
@lftoma google has some [automated tests](https://support.google.com/youtube/answer/132596?hl=en) to determine if advertisements need to be shown. This mainly depends on the domain on which the player is hosted on. You can try [hosting the player on your own domain](https://lonelycpp.github.io/react-native-youtube-iframe/self-host-remote-source) and contacting youtube about advertisements.

**Comment by lftoma** [comment] 2021-04-07 06:08
@LonelyCpp so today I've been trying to figure this out and saw that the small device won't reproduce any ad content at all if it's an iframe https://keen-kirch-690bbb.netlify.app/ if you see this on a phone or a small viewport on your devtools, you won't see any ads, but if you use a desktop size they will start showing. My thought is that the size of viewport is the one that defines ads or not ads, not the caller of the iframe itself (please share any thoughts that you may have) thanks for your answer

**Comment by LonelyCpp** [comment] 2021-04-07 06:28
definitely true

>Player details: We require that the video player appear large enough to promote a positive user experience. We recommend a 560x315 pixel or larger player.

**Comment by lftoma** [comment] 2021-04-07 06:32
@LonelyCpp thanks for your time on confirming this. Guess YouTube want to enforce video watching on their platforms by doing this kind of stuff, I don't blame them but I don't think creators are super happy about. Anyway, thanks for all.

**Comment by ashwanihundwani1986** [comment] 2023-03-23 16:30
@LonelyCpp I am still seeing video unavailable on both Android & iOS for video - nuGafE4JeyI. Can you please help here?

**Comment by psdewar2** [comment] 2023-07-07 15:40
I see this often using version 2.3.0. One hack is to retry loading the component on embed_not_allowed errors.
