### ISSUE TITLE
This video is unavailable

### ISSUE THREAD

**Issue by markus-dopp** [LonelyCpp/react-native-youtube-iframe#167] opened 2021-07-21 20:21 UTC
**Describe the bug**
Since today i'm getting a "This video is unavailable" message from Youtube for all videos. I tried different videos (that have been working before) from multiple devices, networks and emulators.

I'm using the default hosted HTML page.

**Additional context**
react-native-youtube-iframe v2.0.1

**Comment by PabloAbreuC** [comment] 2021-07-21 21:10
Same problem here

**Comment by juddey** [comment] 2021-07-21 22:21
Experiencing this issue also.

**Comment by oeduardoal** [comment] 2021-07-22 00:02
Same here!! I think youtube changed some policy!!

**Comment by oeduardoal** [comment] 2021-07-22 00:45
Hi Guys! I'll open a PR to fix this!!

**Comment by LonelyCpp** [comment] 2021-07-22 02:46
just woke up to this!! Are you all still experiencing this issue? since _it works on my computer 😭_

```js
<YTP 
  height={200} 
  videoId={'tQ0yjYUFKAE'} 
  useLocalHTML={false} // try enabling this prop is all else fails
/>
```

**Comment by kosick** [comment] 2021-07-22 02:57
I updated version to latest 2.1.0 (I used 1.4.0 ver and having this issue.)
And it's working now.

**Comment by alanwjlu** [comment] 2021-07-22 03:32
I was also having the issue and was on 1.4.0. After updating to 2.1.0 it's working again.

**Comment by nguyenvanphuc2203** [comment] 2021-07-22 03:33
same problem here, any way fix it so no need update app?

**Comment by murthy-klapz** [comment] 2021-07-22 05:15
Is there an underlying YouTube API changes that caused the earlier version to crack? Upgrading library isn't always a solution for an app that's already live. 

If the YouTube API changed, there surely would have been a notice sort of thing. 

Looking forward to hear from the lib authors or someone with more insights.

**Comment by sriganesh-nagaraj** [comment] 2021-07-22 06:13
It is not working with our app as well. Upgrading the library isn't viable for us as well

**Comment by murthy-klapz** [comment] 2021-07-22 06:23
> It is not working with our app as well. Upgrading the library isn't viable for us as well

In the interest of time and not letting down customers, we are releasing the app in couple of hours. But would love to know the root cause.

**Comment by LonelyCpp** [comment] 2021-07-22 07:13
Hi guys, here's what I found after a bit of debugging. 

### the cause
the "list" key somehow suddenly rejects empty values.
https://github.com/LonelyCpp/react-native-youtube-iframe/blob/1ed92b576a8459f12e7f4eeb7fe9ffa64677f930/src/PlayerScripts.js#L162

* this would be an empty string if there's no playlist 
* YouTube probably pushed an update to their iframe script that rejects empty "list" key

### why is it working on v2.1.0?
* v2 fetches the HTML script from a remote source and this does not seem to break. **I honestly don't know why.**
* The `useLocalHtml` prop also works because of this commit https://github.com/LonelyCpp/react-native-youtube-iframe/commit/7750ab7dc89af0e1cc6f271c21eb8efdac9c949e that was trying to fix an unrelated issue
* there also seems to be a bug on iOS where `useLocalHtml` does not work. I will be debugging this 

### is there a way to fix this without an app update?
No. The player code is controlled by YouTube itself, I have no control over it.

**Comment by markus-dopp** [comment] 2021-07-22 10:08
> Hi guys, here's what I found after a bit of debugging.
> 
> ### the cause
> the "list" key somehow suddenly rejects empty values.
> https://github.com/LonelyCpp/react-native-youtube-iframe/blob/1ed92b576a8459f12e7f4eeb7fe9ffa64677f930/src/PlayerScripts.js#L162
> 
> * this would be an empty string if there's no playlist
> * YouTube probably pushed an update to their iframe script that rejects empty "list" key
> 
> ### why is it working on v2.1.0?
> * v2 fetches the HTML script from a remote source and this does not seem to break. **I honestly don't know why.**
> * The `useLocalHtml` prop also works because of this commit [7750ab7](https://github.com/LonelyCpp/react-native-youtube-iframe/commit/7750ab7dc89af0e1cc6f271c21eb8efdac9c949e) that was trying to fix an unrelated issue
> * there also seems to be a bug on iOS where `useLocalHtml` does not work. (this is false by default) I will be debugging this
> 
> ### is there a way to fix this without an app update?
> I don't think so.
> 
> The player code is controlled by YouTube itself. Maybe if they rollout a patch to fix this, it will work again - but I have no control over it
> 
> ### links
> [revision history](https://developers.google.com/youtube/player_parameters#Revision_History)
> 
> it looks like `list` and `listType` have received updates on Nov 2020, but hasn't changed since. Not sure why it would suddenly break on July 2021

This 👆 was exactly my issue, once i upgraded and removed the playlist prop it started working again.

**Comment by aakashr143** [comment] 2021-07-22 11:49
Doesnt work even after upgrading to v2.1.0, using Expo SDK 41

**Comment by gabrielcowit** [comment] 2021-07-22 14:11
We had this problem when updated the module: node_modules/react-native-youtube-iframe/dist/index.js: Cannot read property 'cache' of undefined.

Does anyone know how to fix this?

**Comment by aakashr143** [comment] 2021-07-22 14:26
I updated my expo SDK for 41 to 42, but react-native-youtube-iframe hasn't updated, still 1.4.1. How do I update it.

"react-native-web": "~0.13.12",
"react-native-webview": "^11.6.2",
"react-native-youtube-iframe": "^1.4.1",

I tried making a new expo project with SDK 42 and it works but it has v2.1.0

**Comment by LonelyCpp** [comment] 2021-07-22 14:41
@gabrielcowit remove `node_modules`, and reinstall packages

@aakashr143 not sure if what's wrong, you can manually update the version to `"^2.1.0"`

**Comment by PabloAbreuC** [comment] 2021-07-22 19:01
Works perfectely in v2.1.0

**Comment by aakashr143** [comment] 2021-07-22 20:09
This is the error I get when I change the version from 1.4.1 to 2.1.0


npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-youtube-iframe@2.1.1
npm ERR!   node_modules/react-native-youtube-iframe
npm ERR!     react-native-youtube-iframe@"*" from the root project
npm ERR!   2 more (react-native, react-native-web)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=16.5.1" from react-native-web@0.13.18
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"~0.13.12" from the root project
npm ERR!     1 more (react-native-web-webview)

**Comment by aakashr143** [comment] 2021-07-22 20:13
I had to first install react-dom and then update the package

**Comment by vineelk8** [comment] 2021-07-23 13:25
> Hi guys, here's what I found after a bit of debugging.
> 
> ### the cause
> the "list" key somehow suddenly rejects empty values.
> https://github.com/LonelyCpp/react-native-youtube-iframe/blob/1ed92b576a8459f12e7f4eeb7fe9ffa64677f930/src/PlayerScripts.js#L162
> 
> * this would be an empty string if there's no playlist
> * YouTube probably pushed an update to their iframe script that rejects empty "list" key
> 
> ### why is it working on v2.1.0?
> * v2 fetches the HTML script from a remote source and this does not seem to break. This is because the `list` key is set as undefined and not an empty string.
> * The `useLocalHtml` prop also works because of this commit [7750ab7](https://github.com/LonelyCpp/react-native-youtube-iframe/commit/7750ab7dc89af0e1cc6f271c21eb8efdac9c949e) that was trying to fix an unrelated issue
> * ~there also seems to be a bug on iOS where `useLocalHtml` does not work. (this is false by default) I will be debugging this~ (this is unrelated, and fixed [1ad8cec](https://github.com/LonelyCpp/react-native-youtube-iframe/commit/1ad8cec126bf059467a8a117939e8fa7aedc2b95))
> 
> ### is there a way to fix this without an app update?
> I don't think so.
> 
> The player code is controlled by YouTube itself. Maybe if they rollout a patch to fix this, it will work again - but I have no control over it
> 
> ### links
> [revision history](https://developers.google.com/youtube/player_parameters#Revision_History)
> 
> it looks like `list` and `listType` have received updates on Nov 2020, but hasn't changed since. Not sure why it would suddenly break on July 2021
> 
> ### whatever how do I fix this?
> * update yt-iframe to `2.1.1` in package.json (OR `1.4.2` if you're afraid of major version changes)
> * reinstall! (might require a node_modules nuke)
> * TEST
> * push an app update

@LonelyCpp  Can you please let us know whether you can push this fix to earlier versions as well? Because we have live users who are facing this issue.

FYKI: We are using version 1.4.1 in the live app.

**Comment by LonelyCpp** [comment] 2021-07-23 14:58
There's no way I can fix this for 1.4.1 

The the only people who can is youtube

**Comment by vineelk8** [comment] 2021-07-24 05:37
> > It is not working with our app as well. Upgrading the library isn't viable for us as well
> 
> In the interest of time and not letting down customers, we are releasing the app in couple of hours. But would love to know the root cause.

@murthy-klapz even though you give a new release existing users will still have the issue right. Do you have any workaround for that?

**Comment by A7abhilash** [comment] 2021-07-27 03:39
> just woke up to this!! Are you all still experiencing this issue? since _it works on my computer 😭_
> 
> ```js
> <YTP 
>   height={200} 
>   videoId={'tQ0yjYUFKAE'} 
>   useLocalHTML={false} // try changing this prop to "true" if all else fails
> />
> ```

Even I started facing this issue where the videos of the playlist were playing but the individual videos weren't playing at all...

Then this worked for me in the latest update(v2.1.1). Add useLocalHTML={true} props and videos got played properly.

**Comment by Andrew-Chen-Wang** [comment] 2021-07-27 04:01
Perhaps to be a little more backwards compatible is to find the Google Groups Forum for YouTube API and tell them "Hey there's a prob." Unfortunately, I can't seem to find that group -- if it exists that is. But imo a post there would be helpful for existing devs who haven't released the upgrade yet.

**Comment by ddaaggeett** [comment] 2021-07-28 15:29
Ran into this problem too. Will attempt a fix when I can.
Attempted the V2.1.1 update.
Nothing yet.

**Comment by LonelyCpp** [comment] 2021-07-29 13:42
@ddaaggeett looks like you have your own copy of the library. you might find it easier to use `1.4.2` from this branch - https://github.com/LonelyCpp/react-native-youtube-iframe/tree/v1.4.x

**Comment by ddaaggeett** [comment] 2021-07-30 02:05
@LonelyCpp
After deleting node_modules and reinstalled I tested both 1.4.2 and 2.1.1 with the following:

I've been using a copy embedded in my code, yes, with `import YoutubePlayer from "./react-native-youtube-iframe"` but I tested with the NPM package with `import YoutubePlayer from "react-native-youtube-iframe"` which still doesn't work.

**Comment by oussamakenzup** [comment] 2021-08-04 10:55
It doesn't work for me. Updating to 2.1.0 has "This video is unavailable" still.

**Comment by eleonne** [comment] 2021-08-04 16:47
After updating to 2.1.1 it was still not working here. I had to go to 
node_modules/react-native-youtube-iframe/dist/PlayerScripts.js

Then I located this part:
return{htmlString:htmlString,urlEncodedJSON:urlEncodedJSON};

Put a console.warn(htmlString) before and voilá, it works
console.warn(htmlString);return{htmlString:htmlString,urlEncodedJSON:urlEncodedJSON};

I guess the log forced the component to update the html string. It was probably loading the previous version. Also, I removed the console.warn after it worked and all is good here

**Comment by LonelyCpp** [comment] 2021-08-04 16:48
Probably a cache issue with the metro bundler

**Comment by ddaaggeett** [comment] 2021-08-04 18:56
@eleonne , not happening for me
@LonelyCpp , what's the metro bundler?

**Comment by eleonne** [comment] 2021-08-04 19:05
Its cache for sure. I`m just sharing what worked for me. Started debugging and turns out it was cache. In case someone else is stuck, the console.warn in the right place forces the cache to update. Ugly, but works.

**Comment by ddaaggeett** [comment] 2021-08-05 02:28
resetting the cache with Expo v42 is not working `expo r -c`

**Closed** 2021-08-08 18:57 UTC

**Comment by ddaaggeett** [comment] 2021-08-09 15:58
so, how would you recommend cache maintenance?

`npm cache clean --force` - this does not work.

how would you locate the issue with the react-native metro bundler?

**Comment by ddaaggeett** [comment] 2021-08-10 02:22
@eleonne the `console.warn(htmlString)` method is not working, though to me it doesn't make sense why that could possibly be a fix.

The aforementioned [metro bundler troublshooting](https://facebook.github.io/metro/docs/troubleshooting/) also does not work. Caveat: I cannot find the directory to properly perform the following command: `rm -rf /tmp/metro-*`

**Comment by kartavyaparekh96** [comment] 2021-08-11 07:04
Still not working

**Comment by hugoh59** [comment] 2021-09-07 14:55
I'm getting this error `node_modules/react-native-youtube-iframe/dist/index.js: 

```
/Users/hugohouyez/code/hugoh1995/Superprof/node_modules/react-native-youtube-iframe/dist/index.js: Cannot read property 'cache' of undefined

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
``` not sure if it's related.
